//! Enversal Cognitive Engine (Brain)
//!
//! This crate provides the abstract trait `CognitiveEngine` which links
//! Enversal environments directly to Large Language Models (LLMs) to grant
//! agents reasoning and tool-calling capabilities.

use anyhow::Result;
use async_trait::async_trait;
use enversal_core::AgentId;
use serde::{Deserialize, Serialize};

pub mod gemini;
pub mod ollama;
pub mod prompt;

pub use gemini::GeminiEngine;
pub use ollama::OllamaEngine;

/// Represents a distinct tool execution request authorized by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCallRequest {
    /// The name of the registered tool to invoke natively.
    pub tool_name: String,
    /// JSON-encoded arguments provided by the model.
    pub arguments: serde_json::Value,
}

/// The structured output generated by a single iteration of an LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ReasoningOutput {
    /// A conversational or structural text response.
    Message(String),
    /// A decisive command to interact with the environment sandbox.
    ToolCall(ToolCallRequest),
}

/// The context injected into the model representing its current state in the universe.
#[derive(Debug, Clone)]
pub struct AgentContext {
    /// The unique identity of the active agent.
    pub agent_id: AgentId,
    /// The specific model to use for this reasoning step.
    pub model: String,
    /// The foundational directive defining the agent's persona.
    pub system_prompt: String,
    /// New inputs or observations from the environment.
    pub recent_observations: Vec<String>,
}

/// A standard trait interface for mapping any backend AI model (Gemini, Claude, GPT)
/// into the Enversal universe.
///
/// Engines must be inherently asynchronous as they rely on network I/O to the LLM
/// provider.
#[async_trait]
pub trait CognitiveEngine {
    /// Processes the current local `AgentContext` and streams back a tactical decision.
    ///
    /// # Arguments
    /// * `context` - A snapshot of the agent's persona prompt and recent environment history.
    ///
    /// # Returns
    /// Either a structured `ReasoningOutput::ToolCall` dictating an action, or a conversational
    /// message to be broadast on the data plane.
    async fn reason(&self, context: &AgentContext) -> Result<ReasoningOutput>;
}
