//! Primary Enversal CLI Gateway.
//!
//! Provides the native executable used to parse `.yaml` blueprints
//! and push `DeployRequest` messages over gRPC to the daemon service.

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use std::fs;

/// Schema mappings mirroring the `enversal.yaml` format.
pub use enversal_core::manifest::EnversalManifest;

/// Autogenerated Protocol Buffer bindings for the Control Plane.
pub mod control {
    tonic::include_proto!("control");
}

pub mod tui;

use control::environment_control_client::EnvironmentControlClient;
use control::{AttachTelemetryRequest, DeployRequest, InspectRequest, ListRequest};

/// The structure outlining the command-line interface arguments for `clap`.
#[derive(Parser)]
#[command(author, version, about = "Enversal CLI: The Universe for AI Autonomy")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

/// The available subcommands for the Enversal CLI.
#[derive(Subcommand)]
enum Commands {
    /// Start an environment from a blueprint configuration file.
    Run {
        /// Path to the valid `enversal.yaml` blueprint.
        file: String,
    },
    /// List all running environments in the Control Plane
    List,
    /// Inspect the detailed context of a running environment
    Inspect {
        /// The UUID of the environment to inspect
        env_id: String,
    },
}

/// Entrypoint for the Enversal command line client.
#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    match &cli.command {
        Commands::Run { file } => {
            println!("Initializing Enversal universe from {}...", file);

            // Read and deserialize the YAML file
            let content = fs::read_to_string(file)
                .with_context(|| format!("Failed to read blueprint file: {}", file))?;
            let manifest: EnversalManifest = serde_yaml::from_str(&content)
                .context("Failed to parse enversal.yaml blueprint")?;

            println!(
                "Successfully parsed blueprint: {} (Type: {})",
                manifest.environment.name, manifest.environment.env_type
            );
            println!("Leader provisioned: {}", manifest.agents.leader.name);
            println!("\nConnecting to Enversal Control Plane via gRPC...");

            // Connect to the gRPC daemon instance (assumed running on localhost)
            let mut client = EnvironmentControlClient::connect("http://[::1]:50051")
                .await
                .context("Failed to connect to the Enversal Daemon at [::1]:50051. Is the daemon running?")?;

            // Push the parsed environment JSON over gRPC
            let request = tonic::Request::new(DeployRequest {
                env_type: manifest.environment.env_type.clone(),
                blueprint_json: serde_json::to_string(&manifest)?,
            });

            // Await control-plane validation and provisioning
            let response = client.deploy_environment(request).await?;
            let resp = response.into_inner();

            if resp.success {
                println!(
                    "\n[SUCCESS] Environment Deployed! Environment ID: {}",
                    resp.env_id
                );

                println!("Booting Enversal Dashboard Monitor...");
                let req = tonic::Request::new(AttachTelemetryRequest {
                    env_id: resp.env_id.clone(),
                });

                let telemetry_response = client.attach_telemetry(req).await?;
                let stream = telemetry_response.into_inner();

                // Block in the TUI
                tui::run_tui(stream, &resp.env_id)
                    .await
                    .context("Dashboard rendering failed")?;
            } else {
                println!("\n[ERROR] Deployment failed: {}", resp.message);
            }
        }
        Commands::List => {
            println!("Querying Enversal Control Plane for active environments...");
            let mut client = EnvironmentControlClient::connect("http://[::1]:50051")
                .await
                .context("Failed to connect to Daemon")?;

            let response = client
                .list_environments(tonic::Request::new(ListRequest {}))
                .await?;
            let resp = response.into_inner();

            if resp.environments.is_empty() {
                println!("No active environments found.");
            } else {
                println!("{:<40} | {:<10} | {:<10}", "ENV ID", "TYPE", "STATUS");
                println!("{:-<40}-+-{:-<10}-+-{:-<10}", "", "", "");
                for env in resp.environments {
                    println!(
                        "{:<40} | {:<10} | {:<10}",
                        env.env_id, env.env_type, env.status
                    );
                }
            }
        }
        Commands::Inspect { env_id } => {
            println!("Querying deep context for environment: {}...", env_id);
            let mut client = EnvironmentControlClient::connect("http://[::1]:50051")
                .await
                .context("Failed to connect to Daemon")?;

            let response = client
                .inspect_environment(tonic::Request::new(InspectRequest {
                    env_id: env_id.clone(),
                }))
                .await?;
            let resp = response.into_inner();

            if resp.found {
                println!("\n=== Environment Inspect Report ===");
                println!("{}", resp.env_json);
            } else {
                println!(
                    "\n[ERROR] Environment '{}' not found in active registry.",
                    env_id
                );
            }
        }
    }

    Ok(())
}
